query($first: Int!, $after: String, $query: String) {
  customers(first: $first, after: $after, query: $query) {
    edges {
      cursor
      node {
        id
        firstName
        lastName
        email
        phone
        defaultAddress {
          phone
        }
        emailMarketingConsent {
          marketingState
          marketingOptInLevel
          consentUpdatedAt
        }
        smsMarketingConsent {
          marketingState
          marketingOptInLevel
          consentUpdatedAt
          consentCollectedFrom
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
