query getProductDetails($handle: String!, $country: CountryCode)
@inContext(country: $country) {
  productByHandle(handle: $handle) {
    id
    title
    handle
    descriptionHtml
    description
    vendor
    productType
    tags

    options {
      id
      name
      values
    }

    images(first: 250) {
      edges {
        node {
          url
          altText
        }
      }
    }

    variants(first: 250) {
      edges {
        node {
          id
          title
          sku
          availableForSale
          quantityAvailable
          weight
          weightUnit

          price {
            amount
            currencyCode
          }

          compareAtPrice {
            amount
            currencyCode
          }

          compareAtPriceV2 {
            amount
            currencyCode
          }

          image {
            url
            altText
          }

          selectedOptions {
            name
            value
          }
        }
      }
    }

    options {
      name
      values
    }

    metafields(
      identifiers: [
        { namespace: "custom", key: "audio_player" }
        { namespace: "custom", key: "audio_value" }
        { namespace: "custom", key: "available_audio" }
        { namespace: "custom", key: "add_schedule_time_options" }
        { namespace: "custom", key: "trustpilot_logo" }
        { namespace: "custom", key: "email_reading_all_questions" }
        { namespace: "custom", key: "questions" }
      ]
    ) {
      namespace
      key
      type
      value
      reference {
        __typename
        ... on GenericFile {
          url
          mimeType
          originalFileSize
        }
        ... on MediaImage {
          image {
            url
            altText
          }
        }
        ... on Video {
          sources {
            url
            mimeType
          }
        }
      }
    }

    createdAt
    updatedAt
  }
}
