query getProductRecommendations(
  $productId: ID!
  $country: CountryCode
  $intent: ProductRecommendationIntent
) @inContext(country: $country) {
  productRecommendations(productId: $productId, intent: $intent) {
    id
    title
    handle
    availableForSale
    featuredImage {
      url
      altText
    }
    priceRange {
      minVariantPrice {
        amount
        currencyCode
      }
    }
    variants(first: 1) {
      edges {
        node {
          id
          availableForSale
          price {
            amount
            currencyCode
          }
        }
      }
    }
  }
}
